# Generated by Django 3.2.9 on 2021-11-20 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'foods',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'meals',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserDailyMeal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=500)),
                ('note', models.TextField()),
                ('date', models.DateField()),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailymeals.food')),
                ('meal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailymeals.meal')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailymeals.user')),
            ],
            options={
                'db_table': 'users_daily_meals',
            },
        ),
    ]
